-- MySQL Script generated by MySQL Workbench
-- Mon Apr 23 22:54:07 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema issdonaresange
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema issdonaresange
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `issdonaresange` DEFAULT CHARACTER SET utf8 ;
USE `issdonaresange` ;

-- -----------------------------------------------------
-- Table `issdonaresange`.`analiza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `issdonaresange`.`analiza` (
  `idAnaliza` INT(11) NOT NULL AUTO_INCREMENT,
  `grupa` VARCHAR(100) NULL DEFAULT NULL,
  `rh` BIT(2) NULL DEFAULT NULL,
  `Analizacol` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idAnaliza`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `issdonaresange`.`boala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `issdonaresange`.`boala` (
  `nume` VARCHAR(100) NOT NULL,
  `idBoala` INT(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idBoala`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `issdonaresange`.`bolianaliza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `issdonaresange`.`bolianaliza` (
  `idAnaliza` INT(11) NOT NULL,
  `idBoala` INT(11) NOT NULL,
  PRIMARY KEY (`idAnaliza`, `idBoala`),
  INDEX `FK_BoliAnaliza_idx` (`idAnaliza` ASC),
  INDEX `FK_BoliAnaliza_Boala_idx` (`idBoala` ASC),
  CONSTRAINT `FK_BoliAnaliza_Analiza`
    FOREIGN KEY (`idAnaliza`)
    REFERENCES `issdonaresange`.`analiza` (`idAnaliza`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_BoliAnaliza_Boala`
    FOREIGN KEY (`idBoala`)
    REFERENCES `issdonaresange`.`boala` (`idBoala`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `issdonaresange`.`cont`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `issdonaresange`.`cont` (
  `username` VARCHAR(100) NOT NULL,
  `password` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`username`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `issdonaresange`.`donator`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `issdonaresange`.`donator` (
  `idDonator` INT(11) NOT NULL AUTO_INCREMENT,
  `nume` VARCHAR(100) NULL DEFAULT NULL,
  `prenume` VARCHAR(100) NULL DEFAULT NULL,
  `username` VARCHAR(100) NULL DEFAULT NULL,
  `sex` BIT(2) NULL DEFAULT NULL,
  `dataNasterii` DATE NULL DEFAULT NULL,
  `greutate` DOUBLE NULL DEFAULT NULL,
  `puls` INT(11) NULL DEFAULT NULL,
  `tensiuneArterialaSistolica` INT(11) NULL DEFAULT NULL,
  `interventiiChirurgicaleRecente` TINYINT(4) NULL DEFAULT NULL,
  `insarcinata` TINYINT(4) NULL DEFAULT NULL,
  `perioadaLauzie` TINYINT(4) NULL DEFAULT NULL,
  `perioadaMenstruala` TINYINT(4) NULL DEFAULT NULL,
  `consumGrasimi48h` TINYINT(4) NULL DEFAULT NULL,
  `consumBauturiAlcoolice48h` TINYINT(4) NULL DEFAULT NULL,
  `subTratament` TINYINT(4) NULL DEFAULT NULL,
  PRIMARY KEY (`idDonator`),
  INDEX `FK_Donator_Cont_idx` (`username` ASC),
  CONSTRAINT `FK_Donator_Cont`
    FOREIGN KEY (`username`)
    REFERENCES `issdonaresange`.`cont` (`username`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `issdonaresange`.`bolidonator`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `issdonaresange`.`bolidonator` (
  `idDonator` INT(11) NOT NULL,
  `idBoala` INT(11) NOT NULL,
  PRIMARY KEY (`idDonator`, `idBoala`),
  INDEX `FK_BoliDonator_Boala_idx` (`idBoala` ASC),
  INDEX `FK_BoliDonator_Donator_idx` (`idDonator` ASC),
  CONSTRAINT `FK_BoliDonator_Boala`
    FOREIGN KEY (`idBoala`)
    REFERENCES `issdonaresange`.`boala` (`idBoala`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_BoliDonator_Donator`
    FOREIGN KEY (`idDonator`)
    REFERENCES `issdonaresange`.`donator` (`idDonator`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `issdonaresange`.`spital`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `issdonaresange`.`spital` (
  `idSpital` INT(11) NOT NULL,
  `nume` VARCHAR(100) NULL DEFAULT NULL,
  `longitudine` DOUBLE NULL DEFAULT NULL,
  `latitudine` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`idSpital`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `issdonaresange`.`medic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `issdonaresange`.`medic` (
  `idMedic` INT(11) NOT NULL AUTO_INCREMENT,
  `nume` VARCHAR(100) NULL DEFAULT NULL,
  `prenume` VARCHAR(100) NULL DEFAULT NULL,
  `username` VARCHAR(100) NULL DEFAULT NULL,
  `idSpital` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idMedic`),
  INDEX `FK_Cont_idx` (`username` ASC),
  INDEX `FK_Medic_Spital_idx` (`idSpital` ASC),
  CONSTRAINT `FK_Medic_Cont`
    FOREIGN KEY (`username`)
    REFERENCES `issdonaresange`.`cont` (`username`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Medic_Spital`
    FOREIGN KEY (`idSpital`)
    REFERENCES `issdonaresange`.`spital` (`idSpital`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `issdonaresange`.`pacient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `issdonaresange`.`pacient` (
  `idPacient` INT(11) NOT NULL,
  `cnp` VARCHAR(100) NOT NULL,
  `nume` VARCHAR(100) NULL DEFAULT NULL,
  `prenume` VARCHAR(100) NULL DEFAULT NULL,
  `idSpital` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idPacient`),
  UNIQUE INDEX `cnp_UNIQUE` (`cnp` ASC),
  INDEX `FK_Pacient_Spital_idx` (`idSpital` ASC),
  CONSTRAINT `FK_Pacient_Spital`
    FOREIGN KEY (`idSpital`)
    REFERENCES `issdonaresange`.`spital` (`idSpital`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `issdonaresange`.`cerere`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `issdonaresange`.`cerere` (
  `idMedic` INT(11) NOT NULL,
  `prioritate` INT NULL DEFAULT NULL,
  `grupa` VARCHAR(100) NULL DEFAULT NULL,
  `rh` BIT(2) NULL DEFAULT NULL,
  `cantitateCeruta` DOUBLE NULL DEFAULT NULL,
  `cantitateActuala` DOUBLE NULL DEFAULT NULL,
  `dataEfectuare` DATE NULL DEFAULT NULL,
  `idPacient` INT(11) NOT NULL,
  `idCerere` INT NOT NULL,
  INDEX `FK_Cerere_Medic_idx` (`idMedic` ASC),
  INDEX `FK_Cerere_Pacient_idx` (`idPacient` ASC),
  PRIMARY KEY (`idCerere`),
  CONSTRAINT `FK_Cerere_Medic`
    FOREIGN KEY (`idMedic`)
    REFERENCES `issdonaresange`.`medic` (`idMedic`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Cerere_Pacient`
    FOREIGN KEY (`idPacient`)
    REFERENCES `issdonaresange`.`pacient` (`idPacient`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `issdonaresange`.`personaltransfuzii`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `issdonaresange`.`personaltransfuzii` (
  `idPersonalTransfuzii` INT(11) NOT NULL AUTO_INCREMENT,
  `nume` VARCHAR(100) NULL DEFAULT NULL,
  `prenume` VARCHAR(100) NULL DEFAULT NULL,
  `username` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`idPersonalTransfuzii`),
  INDEX `FK_PersonalTransfuzii_Cont_idx` (`username` ASC),
  CONSTRAINT `FK_PersonalTransfuzii_Cont`
    FOREIGN KEY (`username`)
    REFERENCES `issdonaresange`.`cont` (`username`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `issdonaresange`.`preparatsanguin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `issdonaresange`.`preparatsanguin` (
  `tip` VARCHAR(50) NULL DEFAULT NULL,
  `dataPrelevare` DATE NULL DEFAULT NULL,
  `dataExpirare` DATE NULL DEFAULT NULL,
  `idDonator` INT(11) NOT NULL,
  `idAnaliza` INT(11) NOT NULL,
  `cantitate` DOUBLE NULL DEFAULT NULL,
  `idPacient` INT(11) NULL DEFAULT NULL,
  `stagiu` VARCHAR(50) NULL DEFAULT NULL,
  INDEX `FK_PreparatSanguin_Donator_idx` (`idDonator` ASC),
  INDEX `FK_PreparatSanguin_Analiza_idx` (`idAnaliza` ASC),
  PRIMARY KEY (`idDonator`, `idAnaliza`),
  CONSTRAINT `FK_PreparatSanguin_Analiza`
    FOREIGN KEY (`idAnaliza`)
    REFERENCES `issdonaresange`.`analiza` (`idAnaliza`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_PreparatSanguin_Donator`
    FOREIGN KEY (`idDonator`)
    REFERENCES `issdonaresange`.`donator` (`idDonator`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
